# Generated by Django 3.0.3 on 2020-02-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.IntegerField()),
                ('customers', models.IntegerField()),
                ('photographs', models.IntegerField()),
            ],
        ),
    ]
